accessKernelHistory = false
addExtraLineOnCellMerge = true
autoRenderMarkdownCells = false
autoStartDefaultKernel = false
defaultCell = "code"
documentWideUndoRedo = false
enableKernelInitNotification = false
inputHistoryScope = "global"
kernelShutdown = false
maxNumberOutputs = 50
overscanCount = 1
recordTiming = false
renderingLayout = "default"
scrollHeadingToTop = false
scrollPastEnd = true
showEditorForReadOnlyMarkdown = true
showHiddenCellsButton = true
showInputPlaceholder = true
showMinimap = false
sideBySideLeftMarginOverride = "10px"
sideBySideOutputRatio = 1
sideBySideRightMarginOverride = "10px"
windowingMode = "defer"
useSystemClipboardForCells = false

[codeCellConfig]
lineNumbers = false
lineWrap = false

[kernelStatus]
showOnStatusBar = false
showProgress = true
showJumpToRecentExecutionButton = false

[markdownCellConfig."gennaker-tools:snippets"]
snippets = [
    { type = "text", body = "INSERT_THIS", label = "ist" },
]

[rawCellConfig]
lineNumbers = false
matchBrackets = false
